parameters:
#    simple_catalog.example.class: HotDesign\SimpleCatalogBundle\Example

services:
#    simple_catalog.example:
#        class: %simple_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
