imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true


# Parametros de la aplicacion - Definicion de Variables
#
# Dentro del controlador se obtiene con $this->container->getParameter()
#
parameters:
    theme_layout: "HotDesignScThemeBundle:Theme:layout.html.twig"
  
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        nombre_empresa: %nombre_empresa%
        theme_layout_html: %theme_layout%
    exception_controller:  HotDesign\ScThemeBundle\Controller\ExceptionController::showAction

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        path:     %database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        
        
#Doctrine Extensions
stof_doctrine_extensions: 
    orm: 
        default: 
            tree: true
            sluggable: true
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
##SERVICIOS

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }        
    ## El callback para actualizar price_to_uss
    hotdesign.simplecatalog.calc.price_to_uss:
        class: HotDesign\SimpleCatalogBundle\Listener\BaseEntityListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }

            
##AVALANCHE
avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: catalog/cache
    driver:       gd
    filters:
        my_thumb:
            type:    thumbnail
            options: { size: [120, 90], mode: outbound }
            
## FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: HotDesign\ScUserBundle\Entity\User
    
#SwiftMailer
swiftmailer:
    transport:  mail
    #encryption: ssl
    #auth_mode:  login
    #host:       smtp.gmail.com
    #username:   your_username
    #password:   your_password