SimpleCatalogBundle:
    resource: "@SimpleCatalogBundle/Resources/config/routing.yml"
    prefix:   /
    
    
_imagine:
    resource: .
    type:     imagine

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
