parameters:
#    hot_design_sc_theme.example.class: HotDesign\ScThemeBundle\Example

services:
#    hot_design_sc_theme.example:
#        class: %hot_design_sc_theme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
